version: '3.8'

services:
  mtg-deckbuilder:
    build: .
    container_name: mtg-deckbuilder
    stdin_open: true
    tty: true
    volumes:
      # Mount local directories to container for persistence (Linux paths)
      - ${PWD}/deck_files:/app/deck_files
      - ${PWD}/logs:/app/logs
      - ${PWD}/csv_files:/app/csv_files
    environment:
      - PYTHONUNBUFFERED=1
      - TERM=xterm-256color
    # Ensure proper cleanup
    restart: "no"
